"""create all tables

Revision ID: bfb95ba4d856
Revises: 
Create Date: 2026-04-27 23:19:24.699962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfb95ba4d856'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'exported', name='issuestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_number')
    )
    op.create_table('publication_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'issue_number')
    )
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('corporate', 'reader', 'sample', name='recipienttype'), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'monthly', name='recipientfrequency'), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='recipientstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_item_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('default_value', sa.Integer(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('excel_sheet', sa.String(length=50), nullable=True),
    sa.Column('excel_cell', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'sub_category')
    )
    op.create_table('report_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'category', 'sub_category')
    )
    op.create_table('shipping_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'shipped', name='shippingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'recipient_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('new', 'renewal', name='subscriptiontype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipient_created', 'subscriptions', ['recipient_id', 'created_at'], unique=False)
    op.drop_table('user')
    op.drop_index('ftx_name', table_name='product', mysql_prefix='FULLTEXT')
    op.drop_index('idx_lookup', table_name='product')
    op.drop_index('uq_bound', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('series_code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('series_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('product_kind', mysql.ENUM('single', 'subscription', 'bound'), nullable=False),
    sa.Column('media_type', mysql.ENUM('print', 'digital'), nullable=False),
    sa.Column('status', mysql.ENUM('active', 'inactive'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('landing_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('thumbnail_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_bound', 'product', ['series_code', 'media_type', 'product_kind', 'start_date', 'end_date'], unique=True)
    op.create_index('idx_lookup', 'product', ['series_code', 'media_type', 'product_kind', 'start_date', 'end_date'], unique=False)
    op.create_index('ftx_name', 'product', ['series_name', 'display_name'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('user',
    sa.Column('Name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='ç”¨æˆ·å\x90\x8d'),
    sa.Column('Password', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=True, comment='å¯†ç\xa0\x81'),
    sa.Column('DisplayName', mysql.VARCHAR(charset='utf8mb4', length=100), server_default=sa.text("''"), nullable=True, comment='æ˜¾ç¤ºå\x90\x8d'),
    sa.Column('Title', mysql.VARCHAR(charset='utf8mb4', length=100), server_default=sa.text("''"), nullable=True, comment='è\x81Œä½\x8d'),
    sa.Column('Department', mysql.VARCHAR(charset='utf8mb4', length=100), server_default=sa.text("''"), nullable=True, comment='éƒ¨é—¨'),
    sa.Column('Role', mysql.VARCHAR(length=10), server_default=sa.text("'default'"), nullable=True, comment='è§’è‰²'),
    sa.PrimaryKeyConstraint('Name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index('idx_recipient_created', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('shipping_records')
    op.drop_table('report_entries')
    op.drop_table('report_item_templates')
    op.drop_table('recipients')
    op.drop_table('publication_schedule')
    op.drop_table('issues')
    # ### end Alembic commands ###
